### ISSUE TITLE
TNE Errors/Bugs

### ISSUE THREAD

**Issue by RustyDagger** [TheNewEconomy/TNE-Bukkit#26]
As you know I am using that dev build you sent me.
The UUID looks untidy and there is no way in hell the player would know who sent them the money.
http://prntscr.com/8eml48

The Null should also say coins I'm not sure whats up with that it may be just because I Paid my self.

Also your wiki page is missing the permission nodes "tne.money" "tne.bank"   players can not /money or /bank at all with out them. 
without it. I used Pex Debug mode to find it. The node is just that with no extra's

**Comment by creatorfromhell** [comment]
Fixed both the wiki and the UUID appearing, but I won't push the changes until I finish making messages configurable(which is what I'm currently in the process of doing). I appreciate the bug/error finding though. ^^

**Comment by RustyDagger** [comment]
/bank pay did not check nor take money when Used. I have no bypasses.

**Comment by creatorfromhell** [comment]
There is no /bank pay command in TNE currently.

**Comment by RustyDagger** [comment]
I mean Buy ::(

**Comment by creatorfromhell** [comment]
Did it give you any errors/messages?

**Comment by RustyDagger** [comment]
No none. Im running some tests on my local server whilst doing permissions your welcome to join me. As i said before been doing this a long time and have done Bug finding jobs before. I have a teamspeak too if you wish to chat I know id get alot more done :)

**Comment by creatorfromhell** [comment]
I'd be glad to join you on the server, but I can't do teamspeak at this time(around 1am).

**Comment by RustyDagger** [comment]
This is more a feature request but for a Virtual Money system /bank view should not bring up a Chest GUI it turns into a backpack.

The banks are largely useless for a virtual system due to not being able to share it with any one else.
I will be disabling them.

**Comment by creatorfromhell** [comment]
Not all the TNE features will work for everyone, which I why I include the option to disable them as you wish. It really depends on what type of server you're running as to what features would be useful, imo.

**Comment by RustyDagger** [comment]
Yea I just had to tinker with it and look at it to see if it would be something I can use. sadly not. But hey i found a few bugs :8ball:

**Comment by RustyDagger** [comment]
You are still missing "tne.bank" from the wiki page as far as i can see.

**Comment by RustyDagger** [comment]
/theneweconomy reload

requires the permission "tne.admin" Not sure if its checking the tne.admin.reload as well.
I think the sub commands are not working if you dont have the permission for the main command.
Its to do with how you have structured the logic. its not unreasonable. as long as the sub command permissions are being checked.

**Comment by creatorfromhell** [comment]
It checks both the main node(tne.admin) and the sub node(tne.admin.reload).

**Comment by RustyDagger** [comment]
yea i just tested. That works.

Iv disabled Banks in the config and now when i type /money it tells me banks are not enabled in this world.. but /banks still tells me no permission.. Weird seems wrong.

**Comment by creatorfromhell** [comment]
Oops, that's a result of me copy & pasting the classes when I redid the command structure.

**Comment by RustyDagger** [comment]
1:20 Pm here Id imagine your about 12 hours behind me. Im in Western Australia.

**Comment by creatorfromhell** [comment]
https://dl.dropboxusercontent.com/u/33109032/TNE.jar Modified with all the fixes since I have a lot more work to do on the messages system.

**Comment by RustyDagger** [comment]
Another bug for you.

if you have 100 coins and an admin types /money give -101 the player then causes internal errors when they type /money and adding money to their account does not fix the issue. A full database wipe is needed to fix the user.

So for now im just going to be really careful when taking money from players.

**Comment by RustyDagger** [comment]
Enjin Minecraft plugin also seems to have an issue with your API. Or something Its odd.
http://pastebin.com/7V1fS1uG

I think enjins econ features may not be working but I dont really use them so its not a big deal its just making an error...

**Comment by RustyDagger** [comment]
Can you ensure Money is saved then save-all is ran I think some of my players may of lost money on a reboot because they had sold / paid for items in the 5 min before the reboot.

This could lead to Huge Dupe issues if the players realize they could say spend all their money on DIamond blocks after the reboot they get their money back and keep the diamonds. meaning they just got a large pile of diamonds for free..

**Comment by creatorfromhell** [comment]
I'll start looking into these when I get back on my home computer.

**Comment by creatorfromhell** [comment]
I may add more save points into the plugin, but I don't want to save too often, because on a big server this would be rather expensive resource-wise. Also, I was unable to reproduce the money error: http://i.imgur.com/fm49T5O.png. As for the Enjin Plugin, I'm going to look further into this issue.

**Comment by RustyDagger** [comment]
Ok for the money issue try removing a decimal point number. I was being a noob at the time.

/money give -48.8  or even -48.8k

I was really derping. when I broke it.

Regardless The should not be able to go negative money that just leads to all kinds of issues.

**Comment by creatorfromhell** [comment]
Agreed.

**Comment by RustyDagger** [comment]
Honestly the save-all console command is only ran when needed its ran less than your auto save every 5 min. its only entered by a console user or auto script.

**Comment by creatorfromhell** [comment]
https://dl.dropboxusercontent.com/u/33109032/TNE%20(1).jar Is the latest dev build that includes /money take

**Comment by RustyDagger** [comment]
Thanks. I looked into the save-all thing a little more and it seems that the worldsave event is not triggerd by the save-all command and bukkit seems to think its not their issue and wont fix it.
the commands very name is misleading if if does not save plugin data.

maybe force a save ondisable. however thats not called if the server was to crash

**Comment by creatorfromhell** [comment]
TNE has auto-save functionality and save on disable, but I could add an administration command to force save.

**Comment by RustyDagger** [comment]
might be useful i can have it added to my shut down system.

**Comment by creatorfromhell** [comment]
https://dl.dropboxusercontent.com/u/33109032/TNE.jar Updated dev build

**Comment by RustyDagger** [comment]
ARRG major MAjor issue.the 

money give player Number

DOES not work from console...!!!!!!!! Arrrg My Vote rewards !!   its saying im sorry but you cant use that command in my console... WHAT :(

**Comment by creatorfromhell** [comment]
This is a flaw in the new command system, which will be fixed later today after I get a nap since I just got home from work. :P That being said, planned changes for today: administration command additions, message translations implemented, allow commands to be usable via console, and possibly starting on the web interface.

**Comment by RustyDagger** [comment]
Cool Iv disabled my Chest that players click to get rewards. they can just hold onto the keys until you get it fixed. no rush naps are important :P

**Comment by creatorfromhell** [comment]
Had to leave town for a few days, will continue when I get back home.

**Comment by RustyDagger** [comment]
your killing me :( Uh so much rewards broken. Cant be helped...

**Comment by creatorfromhell** [comment]
https://dl.dropboxusercontent.com/u/33109032/TNE.jar - Allows the use of /money give, /money take, /tne reload, /tne save via console.

**Comment by RustyDagger** [comment]
Thank You, You have been Amazing the Last few days.

**Comment by creatorfromhell** [comment]
You're most certainly welcome

**Comment by RustyDagger** [comment]
Command still does not work from console.....
Im still getting a red I'm sorry but you cant use that command message.

Did you link the wrong version?

**Comment by creatorfromhell** [comment]
Nope. I just downloaded it and checked. Double check to make sure you're replacing the old version then reloading your plugins.

**Comment by RustyDagger** [comment]
I just downloaded it again 30 seconds ago and dropped it in to make sure i didnt mix up the versions on my end. I did a full server stop to change the jar.

**Comment by creatorfromhell** [comment]
It's working on my end. http://i.imgur.com/zMfCnu5.png

**Comment by RustyDagger** [comment]
yep iv got it now... i must of derped 2x wow

**Comment by creatorfromhell** [comment]
At least it's working ^^

**Comment by RustyDagger** [comment]
yea :D sorry for being a derp :(

**Comment by creatorfromhell** [comment]
No worries

**Comment by creatorfromhell** [comment]
Dev Build 5:
https://dl.dropboxusercontent.com/u/33109032/TNE.jar
http://i.imgur.com/MZdYyKZ.png

Changes:
- Message Translation
- Ability to set rewards for the new 1.8 mobs(Endermite, Guardian, Rabbit)
- Back-end refactoring

**Comment by RustyDagger** [comment]
Great timing, it seems Mojang things now is a great time to work on the login servers :(

**Comment by creatorfromhell** [comment]
Figures :P

**Comment by RustyDagger** [comment]
Another small issue you may want to fix nothing major.

http://prntscr.com/8fyk0d

Internal Error when trying to pay an offline player You didn't catch the exception so it still prints the internal error to chat and console. you did handle the case just not the error :D

**Comment by creatorfromhell** [comment]
Here's a full list of supported characters/formats:
Colour chart
Char  |   Alt
------|-----------
&b   |  <aqua>
&0   |  <black>
&9   |  <blue>
&3   |  <dark_aqua>
&1   |  <dark_blue>
&8   |  <dark_gray>
&2   |  <dark_green>
&5   |  <dark_purple>
&4   |  <dark_red>
&6   |  <gold>
&7   |  <gray>
&a   |  <green>
&d   |  <purple>
&c   |  <red>
&f   |  <white>
&e   |  <yellow>
&k   |  <magic>
&l   |  <bold>
&o   |  <italic>
&r   |  <reset>
&m   |  <strike>
&n   |  <underline>

**Comment by RustyDagger** [comment]
Thanks, Posts it just after i finish editing the file :D you and the timing today, Offline mode ftw Testing what i can on my own it looks great now.

Except Took And TAKEN

Config:
http://prntscr.com/8fyw7y

Ingame:
http://prntscr.com/8fywxj

**Comment by creatorfromhell** [comment]
Fixed https://dl.dropboxusercontent.com/u/33109032/TNE.jar

**Comment by RustyDagger** [comment]
You are so fast!

**Comment by creatorfromhell** [comment]
Mostly due to a lack of new YouTube content to watch XD

**Comment by RustyDagger** [comment]
Those lines are still not changing for me.. I went to bed with out testing it :( Iv just tried the fix and its still showing default for me.

**Comment by creatorfromhell** [comment]
http://i.imgur.com/85eRBpc.png It's working for me(downloaded the jar off of the dropbox to double check).

**Comment by creatorfromhell** [comment]
I think tomorrow I'll look into starting on land plots, and possibly auctions.

**Comment by RustyDagger** [comment]
THAT image you showed of it working does not SHOW the TWO messages im having issues with working.

Its only the messages from /money take <name> Number that are not working. All the rest work as you showed.

**Comment by RustyDagger** [comment]
I was testing Chestshop on my Local server today to make sure it would all work.
I ran into this issue.  http://prntscr.com/8gm3ke\

As you can see Chest shop seems to be having issues getting the currency name when Notifying the shop owner that have Lost money. When I receive money it works fine. Al tho the wording could use some work :D

**Comment by RustyDagger** [comment]
MAJOR MAJOR MAJOR BUG.
/money pay takes money from the player your trying to pay and gives it to you.

So players can steal money. and it goes negative amounts so they are just cheating money.

**Comment by creatorfromhell** [comment]
Yeah sorry about that I'm going to start looking at these today. I've been busy with work and such.

**Comment by creatorfromhell** [comment]
The bug with pay was a simple mix up with variables(my bad), chestshop I'm unsure at this time, and the messaging one has been fixed. http://i.imgur.com/MIy69cA.png https://dl.dropboxusercontent.com/u/33109032/TNE.jar

**Comment by creatorfromhell** [comment]
If you could, TNE Dev Build 6 needs tested. https://dl.dropboxusercontent.com/u/33109032/TNE.jar
Changes:
  - Added /tne balance <player> [world] - Check the specified player's balance for [world]
  - Added /tne bank <player> [world] - View the specified player's bank for [world]
  - Added access list for possibility to allow players to share banks in the near future, and possibly live shop inventories.

**Comment by RustyDagger** [comment]
tne balance seems to not work with or without the map name.
I cant test the banks as i have them disabled.

http://prntscr.com/8ie0f1

**Comment by RustyDagger** [comment]
Regarding the chest shop issue. I think its to do with Vault some how vault is calling one of its events and your plugin is not giving an answer or its not getting the answer correctly. it seems to be mostly when the user is receiving money. but it does happen sometimes on taking money.

Its getting the Number correctly just not the currency name.

**Comment by creatorfromhell** [comment]
Try this https://dl.dropboxusercontent.com/u/33109032/TNE.jar . It should fix the issues with the tne balance command

**Comment by RustyDagger** [comment]
Check this Out that Null issue is not limited to ChestShop its happening with your own commands.

http://prntscr.com/8j3yrp

Fix it in yours should fix it with chestshop. I hope that helps you debug it some more. one of your functions has a corner case some some kind that's causing it.

maybe its my config setup here is mine.

http://pastebin.com/xusQwmf6

**Comment by creatorfromhell** [comment]
Do you have a currency name set in your per-world configuration(worlds.yml)?

**Comment by creatorfromhell** [comment]
EDIT: Try this, I'm pretty sure I found the issue. https://dl.dropboxusercontent.com/u/33109032/TNE.jar

**Comment by RustyDagger** [comment]
yes that has fixed the NULL issue YAY! High Five.
Thank my admin for pointing out that /money pay was also showing Null I was like Oh really i'm sure the dev would like to know. much easier to debug one plugin than two.

/tne balance also seems to work flawlessly. Its a little slow but I guess thats to be expected.

**Comment by creatorfromhell** [comment]
The speed issues are due to being able to check the balance of offline players too, as opposed to the normal money commands which only let you use them on online players.

**Comment by RustyDagger** [comment]
Yea I assumed as much :D

**Comment by creatorfromhell** [comment]
Will try to pump out Dev Build 7, which will contain land plots tomorrow.

**Comment by RustyDagger** [comment]
To be honest That feature to me seems like it should be another plugin its really got nothing to do with the economy. Except Buying and selling and that should be done via Vault.

**Comment by creatorfromhell** [comment]
Land plots are more or less areas designated for particular uses such as banking, trading, etc. It's on the road map for feature parity with the hMod version of TNE

**Comment by RustyDagger** [comment]
Players some how managed to end up with a ton of decimal places. ( i think chest shop when it calulated part transactions aka its set to be $5 for 3 items but theres only  2 items so it takes the decimal value...

When players get this many decimal places /money /money pay ect starts creating errors when they try to use those commands.

As an admin im unable to take or give them money. 
They can still use shops 

Here is an image of the issue. The Display system is showing exactly what its being told via vault.
http://prntscr.com/8nxiw9

Can we get a Quick fix please Im using flatfile so the files un readable i cant fix the players...

**Comment by creatorfromhell** [comment]
Could you email me your save data file? mailto:daniel.viddy@gmail.com

**Comment by RustyDagger** [comment]
I was able to fix the players data by creating an Admin shop with an item for sale with the exact amount needed to push it back to a whole number.

Basically its only vault requests that are able to push it past the 1 decimal place it supports
I think if you add come rounding to that part of your code it wont happen in the first place.

Im not sure if i have any more players with the issue.

Its not too hard to recreate.

grab any vault shop plugin and set the buy price to something silly like 0.99999999910

Buy it and then you wont be able to /money  or /money pay.

My files quite large some 700 players worth of data.

**Comment by creatorfromhell** [comment]
The max decimal place should be 2 long, but I forget to add the rounding method. It should be a quick fix.

**Comment by creatorfromhell** [comment]
Try this: https://dl.dropboxusercontent.com/u/33109032/TNE.jar

**Comment by RustyDagger** [comment]
I seem to be having an issue.

When the server shuts down it is rolling back the money to some point every time its the same point its rolling back to so its losing hours and hours of changes every restart.

The data saved message is still apearing and the server is using the stop console command to shutdown correctly.

Im not sure on the cause of the issue but it apears to of started from no where.

**Comment by creatorfromhell** [comment]
I've been trying to reproduce the issue you're having, but haven't had any luck as of yet.

**Comment by RustyDagger** [comment]
I dont know how else to help. I can try to grab some log from around the time it shuts down.

**Comment by creatorfromhell** [comment]
Logs may help with pinpointing the issue. TNE might have errored out earlier while running and possibly didn't shut down correctly

**Comment by RustyDagger** [comment]
Here is a full days worth of logs. It will include a few automated restarts. I cant see any thing out of the ordinary apart from enjin still having a fit.

https://dl.dropboxusercontent.com/u/15543708/logs.rar

**Comment by creatorfromhell** [comment]
Are you using the latest build?

**Comment by RustyDagger** [comment]
im using the latest dropbox version you sent me.

**Comment by creatorfromhell** [comment]
Hmm, I still haven't been able to track it down....everything seems to be working fine(auto-save wise, etc), which is strange. Is it still occurring?

**Comment by RustyDagger** [comment]
Yep every restart my money goes back to 9000 something

**Comment by RustyDagger** [comment]
Im rolling back one Build that you sent me. I think when you added the rounding check on all the old existing balances You somehow broke saving. Just an idea Ill have results soon.

**Comment by RustyDagger** [comment]
I went back a Build you sent me and its still doing it. Not saving that is.
My server Does this when it auto reboots or stop/restart is pressed on my control system.

/save-all 
(waits MAX 20 seconds for confirmation)
/stop
(wait MAX 20 seconds for confirmation)

force shut down (if still not closed on its own)

It may of started when i had this changed. I had the /stop added in because of another plugin relying ondisable()

Maybe its your OnDisable code saving the values back to the file as they were when the server first started. instead of pulling all the ones from memory. and flushing them into the DB,

That is honestly the only Thing i can think of that may cause this. at this point in time.

As a Note its also doing it in MYSQL mode not just flatfile.

**Comment by creatorfromhell** [comment]
Alright, been on a small trip(work-related) looking more deeply into this issue now. Should be fixed in a few.

**Comment by creatorfromhell** [comment]
Should be fixed. https://dl.dropboxusercontent.com/u/33109032/TNE.jar Also added /tne backup, which backs your database file(flatfile/sqlite) to a zip file.

**Comment by RustyDagger** [comment]
Fixed it YAY! My players will be very pleased.

**Comment by creatorfromhell** [comment]
Good to hear. ^^ Alpha 2.2 will be available tomorrow so if you notice any last minute bugs just list them here.
--------------------------- Separation between Alpha 2.2 and 3.0(next version) issues --------------------------------

**Comment by creatorfromhell** [comment]
Here's my thoughts for Alpha 3.0,
- Auctions
- Lotteries
- Shop Signs
- Configuration administration in-game

**Comment by RustyDagger** [comment]
Im having an issue. And im sure its related to this plugin.

If my players purchase a lot of items in a short time aka spam a chest shop sign.

It creates HUGE HUGE amounts of lag and even DC's players effectively ass hat players are dam near crashing my server. Thankfully i can see who it is from console. but that does not resolve the issue it only puts a bandaid on it.

Im saving in flatfile and im sure I have some 1100 player entries my thoughts are that its the processing of checking the players balance between transactions that's causing the performance hit.

I could try moving to mysql but i cant be loosing my data...

**Comment by creatorfromhell** [comment]
Will look into this when I get home. I may have to send you a test build to get some debug info though

**Comment by RustyDagger** [comment]
sure thing i understand you cant really test it on the scale i can im all for helping as you know

**Comment by creatorfromhell** [comment]
Sorry about the delay, I got completely sidetracked on a new project I was testing. Will send the build first thing in the morning

**Comment by creatorfromhell** [comment]
https://www.dropbox.com/s/vjkralkwzwds1xb/TNE.jar?dl=0 Try this for a bit and paste some of the server logs. It should output something like fundsRemove time taken: <insert time here>

**Comment by RustyDagger** [comment]
I downloaded and installed that jar.. But i cant seem to see any on the FundsRemove  messages in console your talking about. However Whilst trying to cause the Debug to show. We managed to crash the server our selves only this time i was able to get the LOG.

http://pastebin.com/zRYUKAx0

Something about TNE revival and some vault return packet mentioned in the topish area of the log. maybe that will help you track the issue down.

**Comment by creatorfromhell** [comment]
It has something to with when TNE gets the player's UUID since chest shop apparently doesn't use UUIDs(?). I've been trying to reproduce the error, but haven't been able to so it could possibly just be the amount of queries being send to the Mojang Site from your server. I've added a cache so that it now only calls the site once/user. Hopefully this'll solve the issue.

**Comment by creatorfromhell** [comment]
Try using https://www.spigotmc.org/resources/the-new-economy.7805/update?update=53941

**Comment by RustyDagger** [comment]
Yeah it seems as tho both chestshop and LWC have not moved with the times and added UUID support.
I have nearly 40 plugins on the server including some made just for US. To put it this way 50+ permissions checks are ran for every chat message. Due to EzranksPro. the servers under some load. its 4gb ram and i have it down to 50 slots for good reason.

Ill give the build a Go and see how it goes. I need a few sets of hands to test well. bit hard to monitor console and spam a chest shop 30 ish times at once.

**Comment by creatorfromhell** [comment]
Yeah, a lot of plugins haven't moved with the times, most likely due to everyone wanting to wait for the official Mojang API, but it's not really hard to support...The hardest part is converting all of your old data to use UUIDS. Good news is there's some interest in someone else joining the TNE development team, so when I can't respond he can if he decides to join. :P

**Comment by RustyDagger** [comment]
heh iv never had issues reaching you :P More heads never hurts tho.

Im just updating some mcmmo stuff some permissions and logblock Its only me on my server rest went to bed. welcome to join me. mc.ozcraft.com.au

**Comment by creatorfromhell** [comment]
BTW, just wondering if you had any feature requests for Alpha 3.

**Comment by RustyDagger** [comment]
No not that i can think of at this time. iv just got back from holiday yay... a truck load of updates waiting for me now i remember why i keep ontop of them.

**Comment by creatorfromhell** [comment]
Sorry for the lack of updates, but I've been reworking my site and creating a new Bukkit plugin, which I believe a lot of servers will use. ^^

**Comment by RustyDagger** [comment]
All good its been running fine. Until 2 days ago I had to downsize my server due to a lack of donations staff and not working somehow in all the map changing and permissions swapping the Database got corrupted or something and it was internal errors every time you typed a money command. I was making large changes to the server any way so i just did a wipe. and its fine now.

**Comment by creatorfromhell** [comment]
Hopefully there's not a repeat, but I'm probably going to make some utility for reading .tne files soon. I've just gotta get my second plugin into the testing phase( which should be within the next few days) then I'll return focus to pushing TNE Alpha 3 out, along with the web companion app.

**Comment by creatorfromhell** [comment]
I might need someone to help do some final testing on 54fa9da05ffd65e746ffe77c69e0142f642b0882 if you're interested.
